// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	BROWSERCAT_KEY: string;
	BROWSER: Fetcher;
	BROWSER_KV_DEMO: KVNamespace;
}
