// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	WEB_TOKEN_WORKFLOW: Workflow;
	SPOTIFY_WEB_TOKEN: KVNamespace;
}
